### ISSUE TITLE
How to add descriptions(SEO) to each pages?

### ISSUE THREAD

**Issue by bousouninjin** [justinformentin/gatsby-v2-tutorial-starter#13]
Description of home page(/) and post five is same.
How to add description to each pages?

**Comment by justinformentin** [comment]
If you look at the `/templates/post`, you'll find the `SEO` components being used. 
https://github.com/justinformentin/gatsby-v2-tutorial-starter/blob/6bcb8e47f330de1ac95a46976422add5a2a2923a/src/templates/post.jsx

` <SEO
        title={title}
        description={description || excerpt || ' '}
...
`
And you can change the description there either programmatically or by hard coding it.

**Comment by bousouninjin** [comment]
Thank you very much justin, it worked!
