### ISSUE TITLE
About page body text not responsive

### ISSUE THREAD

**Issue by jagatfx** [justinformentin/gatsby-v2-tutorial-starter#2]
Great starter theme. I found an issue I thought you might want to fix.

# Bug Description

The About page displays body text that is not responsive on mobile screens similar in size to iPhone 6/7/8. The text is displayed with one character per line.

<img width="268" alt="screen shot 2019-01-10 at 10 52 14 am" src="https://user-images.githubusercontent.com/198755/50980428-a96bb880-14c6-11e9-93ca-2197ab0c0d51.png">

# To Reproduce

Visit https://gatsby-tutorial-starter.netlify.com/about in Chrome. Enable device toolbar and select iPhone 6/7/8 or visit page on one of those mobile devices in Safari. 

# Expected Behavior

The body text of the About page is responsive to smaller screens.

**Comment by justinformentin** [comment]
Ah, thanks for pointing that out. I'll fix it as soon as I can.
