### ISSUE TITLE
Support to add gif or video

### ISSUE THREAD

**Issue by d78ui98** [justinformentin/gatsby-v2-tutorial-starter#5]
Currently, if I add a video or gif file it is not working.
It shows someone thing like this in the browser withn deployed with `gatsby develop`

![gatsby-image](https://user-images.githubusercontent.com/27950739/53843481-8e01c300-3fc8-11e9-9131-86fea84d778d.png)

Please provide any solution.
Btw gatsby-v2-tutorial-starter is amazing. :)
works most of time perfectly.
I am just faceing some minor issues.

**Comment by justinformentin** [comment]
Did some digging and it looks like someone actually released some plugins to help with this. https://github.com/gatsbyjs/gatsby/issues/3346

**Comment by d78ui98** [comment]
Thanks for the help :)
